version: "3"

services:
  app:
    image: "docker-spring-boot-postgres:latest"
    build:
      context: ./docker/kotlin
    container_name: app
    depends_on:
      - mysql
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080

  mysql:
    image: mysql:8.0.20
    environment:
      MYSQL_DATABASE: platform_sam@ple
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3306
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    container_name: mysql
    restart: always

  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
