version: "3"

services:
  app:
    # image: "docker-spring-boot-postgres:latest"
    image: "${AWS_ECR_IMAGE_APP}"
    build:
      context: ./docker/kotlin
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080

  db:
    # image: "postgres:13.1-alpine"
    # public レジストリを公開するとやばいので、github secretsへ
    image: "${AWS_ECR_IMAGE_DB}"
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
