name: development build & deploy
on: push
jobs:
  build_backend:
    runs-on: ubuntu-latest
    steps:
      # Pre-build
      - name: Checkout repo
        uses: actions/checkout@v2
        
        
      # Build
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build
        
        
      # Pre-deploy
      - name: Pre-deploy flow # デプロイ前の設定
        run: |
          cp ./build/libs/*.jar ./docker/kotlin
          
          
      # Deploy
      - name: Configure AWS Credentials # AWSアクセス権限設定
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
        
      - name: Login to Amazon ECR # ECRログイン処理
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
    
      - name: Backend Kotlin ...Build, tag, and push image to Amazon ECR # ECRイメージPush
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
        run: |
          cd docker/kotlin
          echo 'ここでpwd'
          pwd
          echo 'ここでls'
          ls
          IMAGE_TAG=latest
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f docker/kotlin/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

#       - name: Render Amazon ECS task definition # ECSタスク定義ファイルレンダリング
#         id: render-container
#         uses: aws-actions/amazon-ecs-render-task-definition@v1
#         with:
#           task-definition: aws/task-definition.json # レポジトリ以下のタスク定義ファイルがあるPath
#           container-name: app-container-name
#           image: XXXXXXXXXXXX.dkr.ecr.ap-northeast-1.amazonaws.com/app:latest

#       - name: Deploy to Amazon ECS service # ECSサービスデプロイ
#         uses: aws-actions/amazon-ecs-deploy-task-definition@v1
#         with:
#           task-definition: ${{ steps.render-container.outputs.task-definition }}
#           service: app-service
#           cluster: app-ecs-cluster
          
          
        
        
#  frontend build(comment out it if necessary)
#  build_frontend:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: "14"
#      - run: npm install
#        working-directory: ./src/main/frontend
#      - run: npm run lint
#        working-directory: ./src/main/frontend
